MDBoxLayout:
    id: boxsave
    orientation:"vertical"
    spacing:"30dp"
    size_hint_y:None
    height:"120dp"
    MDLabel:
        id: lab
        text: ''
    MDProgressBar:
        id: prog
        value: 
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
         
    #MDRaisedButton:
    #    text: 'Cancel'    
    #MDRaisedButton:
    #    text: 'Submit' 
    #    size_hint_x: 0.4     